version: "3"
services:
  postgis:
    image: kartoza/postgis:15-3.3
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_DBNAME=${G3WSUITE_POSTGRES_DBNAME},${TAILINGS_POSTGRES_DBNAME},data_testing,data_production
      - POSTGRES_USER=${G3WSUITE_POSTGRES_USER_LOCAL}
      - POSTGRES_PASS=${G3WSUITE_POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
      - RUN_AS_ROOT=true
      - FORCE_SSL=False
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ${PG_VOLUME}:/var/lib/postgresql
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 3
      test: "PGPASSWORD=${G3WSUITE_POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${G3WSUITE_POSTGRES_USER_LOCAL} -d ${G3WSUITE_POSTGRES_DBNAME}"
    networks:
      internal:

  g3w-suite:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    environment:
      - DISPLAY=:99
      - G3WSUITE_TILECACHE_PATH
      - G3WSUITE_QDJANGO_SERVER_URL
      - G3WSUITE_POSTGRES_DBNAME
      - G3WSUITE_POSTGRES_USER
      - G3WSUITE_POSTGRES_USER_LOCAL
      - G3WSUITE_POSTGRES_PASS
      - G3WSUITE_POSTGRES_HOST
      - G3WSUITE_POSTGRES_PORT
      - TAILINGS_POSTGRES_DBNAME
      - TAILINGS_POSTGRES_USER
      - TAILINGS_POSTGRES_USER_LOCAL
      - TAILINGS_POSTGRES_PASS
      - TAILINGS_POSTGRES_HOST
      - TAILINGS_POSTGRES_PORT
      - G3WSUITE_ORS_API_ENDPOINT
      - G3WSUITE_ORS_API_KEY
      - G3WSUITE_DEBUG
      - TILESTACHE_CACHE_BUFFER_SIZE
      - TILESTACHE_CACHE_TOKEN
      - G3WSUITE_GUNICORN_NUM_WORKERS
      - G3WSUITE_GUNICORN_MAX_REQUESTS
      - G3WSUITE_GUNICORN_TIMEOUT
      - FRONTEND
      - PGSERVICEFILE
      - QGIS_OPTIONS_PATH=/shared-volume/
      - QGIS_SERVER_LOG_FILE
      - QGIS_SERVER_LOG_LEVEL
      - G3WSUITE_CONSUMER=1
    expose:
      - "8000"
    ports:
      - "8000:8000"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/node_modules:/code/node_modules
      - ./docker/g3w-suite/overrides/static:/code/static:ro
      - ./docker/g3w-suite/overrides/templates:/code/templates:ro
      - ./docker/g3w-suite/settings_docker.py:/code/g3w-admin/base/settings/local_settings.py
      - ./scripts:/code/ci_scripts
      - ./secrets/pg_service.conf:${PGSERVICEFILE}
      - ./qgis/QGIS3.ini:/shared-volume/QGIS/QGIS3.ini
#      Uncomment these lines if you want to mount G3W Admin, dam_monitor, or g3w api when developing
#      - ${G3WSUITE_LOCAL_CODE_PATH}:/code
#      - ${DAM_MONITOR_CODE_PATH}:/code/g3w-admin/dam_monitor
#      - ${G3W_API_CODE_PATH}:/code/g3w-admin/g3w_api

    entrypoint: /scripts/docker-entrypoint-dev.sh

    networks:
      internal:

  redis:
    image: redis:7.4.0
    expose:
      - 6379
    networks:
      internal:
    restart: always

  # Asynchronous tasks consumer (run_huey)
  g3w-suite-consumer:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
    environment:
      - DISPLAY=:99
      - G3WSUITE_TILECACHE_PATH
      - G3WSUITE_QDJANGO_SERVER_URL
      - G3WSUITE_POSTGRES_DBNAME
      - G3WSUITE_POSTGRES_USER
      - G3WSUITE_POSTGRES_USER_LOCAL
      - G3WSUITE_POSTGRES_PASS
      - G3WSUITE_POSTGRES_HOST
      - G3WSUITE_POSTGRES_PORT
      - TAILINGS_POSTGRES_DBNAME
      - TAILINGS_POSTGRES_USER
      - TAILINGS_POSTGRES_USER_LOCAL
      - TAILINGS_POSTGRES_PASS
      - TAILINGS_POSTGRES_HOST
      - TAILINGS_POSTGRES_PORT
      - G3WSUITE_ORS_API_ENDPOINT
      - G3WSUITE_ORS_API_KEY
      - G3WSUITE_DEBUG
      - TILESTACHE_CACHE_BUFFER_SIZE
      - TILESTACHE_CACHE_TOKEN
      - G3WSUITE_GUNICORN_NUM_WORKERS
      - G3WSUITE_GUNICORN_MAX_REQUESTS
      - G3WSUITE_GUNICORN_TIMEOUT
      - FRONTEND
      - PGSERVICEFILE
      - QGIS_OPTIONS_PATH=/shared-volume/
      - QGIS_SERVER_LOG_FILE
      - QGIS_SERVER_LOG_LEVEL
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    entrypoint: /scripts/docker-consumer-entrypoint.sh
    depends_on:
      - g3w-suite
      - redis
    volumes:
      - ${WEBGIS_DOCKER_SHARED_VOLUME}:/shared-volume
      - ${WEBGIS_DOCKER_SHARED_VOLUME}/node_modules:/code/node_modules
      - ./docker/g3w-suite/overrides/static:/code/static:ro
      - ./docker/g3w-suite/overrides/templates:/code/templates:ro
      - ./docker/g3w-suite/settings_docker.py:/code/g3w-admin/base/settings/local_settings.py
      - ./secrets/pg_service.conf:${PGSERVICEFILE}
      - ./qgis/QGIS3.ini:/shared-volume/QGIS/QGIS3.ini
#      Uncomment these lines if you want to mount G3W Admin, dam_monitor, or g3w api when developing
#      - ${G3WSUITE_LOCAL_CODE_PATH}:/code
#      - ${DAM_MONITOR_CODE_PATH}:/code/g3w-admin/dam_monitor
#      - ${G3W_API_CODE_PATH}:/code/g3w-admin/g3w_api
    networks:
      internal:

volumes:
  g3w-suite-data:
  g3wsuite-pg-data:
  g3wsuite-eoi-db-data:

networks:
  internal:
